// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodleSystem.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoodleSystem.Infrastructure.Migrations
{
    [DbContext(typeof(MoodleDbContext))]
    [Migration("20251222172541_seed_initial_data3")]
    partial class seed_initial_data3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoodleSystem.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("content");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("announcements", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "sadrzaj 1 annon",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7937),
                            Title = "Kolokvij1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "sadrzaj 2 annon",
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7939),
                            Title = "Kolokvij2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "sadrzaj 3 annon",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7940),
                            Title = "Kolokvij3"
                        });
                });

            modelBuilder.Entity("MoodleSystem.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("professor_id");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("courses", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7862),
                            Name = "Programiranje",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7863),
                            Name = "Programiranje za Unix",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7864),
                            Name = "Programiranje za Internet",
                            ProfessorId = 3
                        });
                });

            modelBuilder.Entity("MoodleSystem.Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("materials", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7899),
                            Name = "Materijal1",
                            Url = "https://url1.hr"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7901),
                            Name = "Materijal2",
                            Url = "https://url2.hr"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7902),
                            Name = "Materijal3",
                            Url = "https://url3.hr"
                        });
                });

            modelBuilder.Entity("MoodleSystem.Domain.Entities.PrivateMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_id");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("private_messages", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Sadrzaj privatne poruke 1",
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7916),
                            ReceiverId = 2,
                            SenderId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Sadrzaj privatne poruke 2",
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7917),
                            ReceiverId = 3,
                            SenderId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Sadrzaj privatne poruke 3",
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7918),
                            ReceiverId = 1,
                            SenderId = 2
                        });
                });

            modelBuilder.Entity("MoodleSystem.Domain.Entities.UserCourse", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("user_courses", "public");

                    b.HasData(
                        new
                        {
                            UserId = 4,
                            CourseId = 1
                        },
                        new
                        {
                            UserId = 5,
                            CourseId = 1
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7757),
                            Email = "admin@fesb.hr",
                            FirstName = "Lolek",
                            LastName = "Bokic",
                            Password = "ananas",
                            Role = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7761),
                            Email = "profesorr@fesb.hr",
                            FirstName = "Boban",
                            LastName = "Porke",
                            Password = "ananas",
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7762),
                            Email = "elprofesorr@fesb.hr",
                            FirstName = "Ivica",
                            LastName = "Porke",
                            Password = "ananas",
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7764),
                            Email = "dinastud@fesb.hr",
                            FirstName = "Dina",
                            LastName = "Gladan",
                            Password = "ananas",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 22, 17, 25, 41, 336, DateTimeKind.Utc).AddTicks(7765),
                            Email = "dujestud@fesb.hr",
                            FirstName = "Duje",
                            LastName = "Nincevic",
                            Password = "ananas",
                            Role = 1
                        });
                });

            modelBuilder.Entity("MoodleSystem.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("MoodleSystem.Domain.Entities.Course", "Course")
                        .WithMany("Announcements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MoodleSystem.Domain.Entities.Course", b =>
                {
                    b.HasOne("User", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("MoodleSystem.Domain.Entities.Material", b =>
                {
                    b.HasOne("MoodleSystem.Domain.Entities.Course", "Course")
                        .WithMany("Materials")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MoodleSystem.Domain.Entities.PrivateMessage", b =>
                {
                    b.HasOne("User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MoodleSystem.Domain.Entities.UserCourse", b =>
                {
                    b.HasOne("MoodleSystem.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodleSystem.Domain.Entities.Course", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Enrollments");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
